name: go

on:
  push:
    branches: [ v3 ]
  pull_request:
    branches: [ v3 ]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        go: ['1.20']
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.5'

      - name: Test
        run: go test -v ./...
